vpn:
  build: .
  #command: bash -c "NODE_PATH=/node_modules node /ui/server.js"
  ports:
    - "8080:8080"
  privileged: true
  environment:
    - USER
    - PASS
proxy:
  image: goproxy
  net: container:vpn
  command: bash -c "app -v"
