vpn:
  build: .
  #command: bash -c "NODE_PATH=/node_modules node /ui/server.js"
  ports:
    - "6543:6543"
  privileged: true
  environment:
    - USER
    - PASS
    - SERVER
proxy:
  build: ./goproxy
  dockerfile: Dockerfile
  net: container:vpn
  command: app -v -listen :6543
