vpn:
  build: .
  #command: bash -c "NODE_PATH=/node_modules node /ui/server.js"
  ports:
    - "6543:3128"
  privileged: true
  environment:
    - USER
    - PASS
    - SERVER
# squid:
#   image: sameersbn/squid:3.3.8-14
#   net: container:vpn
#   command: -d ALL,9
proxy:
  build: ./goproxy
  dockerfile: Dockerfile
  net: container:vpn
  command: app -listen :3128 -v
filter:
  build: ./filterproxy
  dockerfile: Dockerfile
  command: app -listen :7800 -config proxy.cfg
  ports:
    - "7800:7800"
    - "6060:6060"
  links:
    - vpn
