vpn:
  build: .
  #command: bash -c "NODE_PATH=/node_modules node /ui/server.js"
  ports:
    - "7999:8080"
  privileged: true
  environment:
    - USER
    - PASS
    - SERVER
proxy:
  build: ./goproxy
  dockerfile: Dockerfile
  net: container:vpn
